### PR TITLE
Add initial website structure

### LINKED ISSUE #2: New theme
I think we should go with an existing theme, get the site contents up, and think about customization later.

Here's what I am planning to try (in this order)
- https://github.com/aaranxu/adidoks
- https://github.com/codeandmedia/zola_easydocs_theme
- https://github.com/jakeswenson/zola-just-the-docs

Any other recommendations?

### PR DESCRIPTION
**Pull request by leejuyuu**
- Use https://github.com/aaranxu/adidoks theme by including a Git submodule. Remove the temporary hallo theme. Modify the config.toml according to the provided example.
- Add home page, installation guide, contribution guides, FAQs, and authors.
- Add favicons generated from the SVG icon with
      https://realfavicongenerator.net.
      
      
Closes #2.

### CODE REVIEW

**Comment by leejuyuu** [comment]
@mmahmoudian It seems that I need approval to trigger CI. Could you help?

**Comment by mmahmoudian** [comment]
This is a massive change and I cannot personally review all 66 files 😅 bit the config.toml looked right. Let's see if it builds and then we merge. 

Thanks for all your efforts.

**Comment by leejuyuu** [comment]
> This is a massive change and I cannot personally review all 66 files 😅 bit the config.toml looked right. Let's see if it builds and then we merge. 
> 
> Thanks for all your efforts.

Thanks! It might seem a lot, but most of the change counts come from the deletion of the old theme. I believe the focus for review is the /content folder.

**Comment by leejuyuu** [comment]
The actual contents like blogs and tutorials will come in the next PR.

**Pull request merged**
